In [2]:
from __future__ import print_function, absolute_import
from gm.api import *
set_token("59e9c8cd18899c191fa133d4cdb08d66efba3dd9")

history_data = history(symbol='SHSE.118037', frequency='1m', start_time='2026-01-20',end_time='2026-04-20', df=True)

In [3]:
history_data

,symbol,frequency,open,high,low,close,volume,amount,pre_close,position,bob,eob
0,SHSE.118037,60s,139.855,139.980,139.239,139.980,7640,1067796.0,0.0,0,2026-01-20 09:30:00+08:00,2026-01-20 09:31:00+08:00
1,SHSE.118037,60s,139.981,140.158,139.848,140.158,8690,1215921.0,0.0,0,2026-01-20 09:31:00+08:00,2026-01-20 09:32:00+08:00
2,SHSE.118037,60s,140.159,140.354,140.100,140.274,3530,495012.0,0.0,0,2026-01-20 09:32:00+08:00,2026-01-20 09:33:00+08:00
3,SHSE.118037,60s,140.300,140.383,139.999,139.999,4910,688345.0,0.0,0,2026-01-20 09:33:00+08:00,2026-01-20 09:34:00+08:00
4,SHSE.118037,60s,139.963,140.383,139.963,140.227,5080,712315.0,0.0,0,2026-01-20 09:34:00+08:00,2026-01-20 09:35:00+08:00
...,...,...,...,...,...,...,...,...,...,...,...,...
12163,SHSE.118037,60s,135.771,135.794,135.707,135.794,530,71957.0,0.0,0,2026-04-09 14:55:00+08:00,2026-04-09 14:56:00+08:00
12164,SHSE.118037,60s,135.792,135.931,135.792,135.832,1190,161678.0,0.0,0,2026-04-09 14:56:00+08:00,2026-04-09 14:57:00+08:00
12165,SHSE.118037,60s,135.862,135.862,135.734,135.734,370,50251.0,0.0,0,2026-04-09 14:57:00+08:00,2026-04-09 14:58:00+08:00
12166,SHSE.118037,60s,135.853,136.075,135.853,136.000,860,116938.0,0.0,0,2026-04-09 14:58:00+08:00,2026-04-09 14:59:00+08:00
12167,SHSE.118037,60s,135.856,136.036,135.856,136.036,330,44893.0,0.0,0,2026-04-09 14:59:00+08:00,2026-04-09 15:00:00+08:00

In [10]:
# 获取可转债代码列表
bond_codes = ['SHSE.127033']

# 获取当日换手率
sec_type1 = 103001  # 证券类型为债券
exchanges = ['SZSE', 'SHSE']  # 交易所代码，深交所和上交所
skip_suspended = True  # 跳过停牌
skip_st = True  # 跳过ST股票
trade_date = '20231001'  # 替换为实际的交易日日期
df = True  # 返回DataFrame格式

# 获取当日换手率
turnover_rates = get_symbols(sec_type1, sec_type2=None, exchanges=exchanges, symbols=bond_codes, skip_suspended=skip_suspended, skip_st=skip_st, trade_date=trade_date, df=df)

In [11]:
turnover_rates

Empty DataFrame
Columns: []
Index: []

In [5]:
from __future__ import print_function, absolute_import
from datetime import datetime, timedelta
from gm.api import *
import pandas as pd

# 设置API token
set_token("59e9c8cd18899c191fa133d4cdb08d66efba3dd9")

# 获取今天的日期
today = datetime.today()
# 计算60天前的日期
sixty_days_ago = today - timedelta(days=60)

# 将日期格式化为字符串，用于API请求
today_str = today.strftime("%Y-%m-%d")
sixty_days_ago_str = sixty_days_ago.strftime("%Y-%m-%d")

# 获取沪深300指数的成分股
index_code = 'SHSE.000300'  # 沪深300指数的代码
constituents = stk_get_index_constituents(index_code)

# 获取成分股的代码列表
list1 = list(constituents['symbol'])

# 获取最近60天的历史数据
history_data = history(symbol=list1, frequency='1d', start_time=sixty_days_ago_str, end_time=today_str, df=True)

# 定义一个函数来计算60日最低价并判断是否处于新低
def find_60_day_low_stocks(history_data):
    low_stocks = []
    for symbol in history_data['symbol'].unique():
        stock_data = history_data[history_data['symbol'] == symbol]
        # 计算60日最低价
        stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
        # 获取最新一天的数据
        latest_data = stock_data.iloc[-1]
        # 判断是否处于60日新低
        if latest_data['low'] == latest_data['60_day_low']:
            low_stocks.append((symbol, latest_data['eob'], latest_data['low']))
    return low_stocks

# 找出最近60日新低的股票
low_stocks = find_60_day_low_stocks(history_data)

# 将结果转换为DataFrame
low_stocks_df = pd.DataFrame(low_stocks, columns=['股票代码', '日期', '最低价'])

# 打印结果
print(low_stocks_df)

In [6]:
history_data

,symbol,frequency,open,high,low,close,volume,amount,pre_close,position,bob,eob
0,SHSE.601698,1d,15.26,15.43,15.20,15.28,15208508,2.33126660e+08,15.25,0,2024-08-19 00:00:00+08:00,2024-08-19 00:00:00+08:00
1,SZSE.002371,1d,316.50,319.88,313.69,316.20,2768600,8.78001814e+08,316.06,0,2024-08-19 00:00:00+08:00,2024-08-19 00:00:00+08:00
2,SHSE.688303,1d,19.99,20.20,19.50,19.66,3321323,6.54552336e+07,19.99,0,2024-08-19 00:00:00+08:00,2024-08-19 00:00:00+08:00
3,SHSE.601607,1d,19.76,19.98,19.59,19.73,6242336,1.23373516e+08,19.78,0,2024-08-19 00:00:00+08:00,2024-08-19 00:00:00+08:00
4,SHSE.600111,1d,16.95,17.11,16.92,16.95,9095266,1.54686730e+08,16.94,0,2024-08-19 00:00:00+08:00,2024-08-19 00:00:00+08:00
...,...,...,...,...,...,...,...,...,...,...,...,...
11031,SHSE.688303,1d,25.30,25.50,24.20,24.28,8338895,2.06412848e+08,25.17,0,2024-10-17 00:00:00+08:00,2024-10-17 00:00:00+08:00
11032,SHSE.601898,1d,13.90,14.23,13.67,13.68,18932352,2.63883476e+08,13.81,0,2024-10-17 00:00:00+08:00,2024-10-17 00:00:00+08:00
11033,SHSE.600519,1d,1537.00,1537.66,1493.41,1494.60,3945955,5.96477896e+09,1522.50,0,2024-10-17 00:00:00+08:00,2024-10-17 00:00:00+08:00
11034,SHSE.600845,1d,28.00,28.67,27.69,27.94,25965590,7.30691080e+08,27.78,0,2024-10-17 00:00:00+08:00,2024-10-17 00:00:00+08:00
11035,SZSE.301269,1d,91.50,92.70,89.11,89.30,3489253,3.17538109e+08,89.00,0,2024-10-17 00:00:00+08:00,2024-10-17 00:00:00+08:00

C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:

Empty DataFrame
Columns: [股票代码, 日期, 最低价]
Index: []

C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_data.loc[:, '60_day_low'] = stock_data['low'].rolling(window=60).min()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_13636\3504785888.py:7: SettingWithCopyWarning:

In [2]:
history_data

,symbol,frequency,open,high,low,close,volume,amount,pre_close,position,bob,eob
0,SHSE.600426,1d,28.78,28.78,25.78,26.60,81672793,2.20831537e+09,26.19,0,2024-10-08 00:00:00+08:00,2024-10-08 00:00:00+08:00
1,SZSE.301269,1d,111.61,111.61,103.80,111.61,11340360,1.25471976e+09,93.01,0,2024-10-08 00:00:00+08:00,2024-10-08 00:00:00+08:00
2,SZSE.300999,1d,42.59,42.59,37.89,41.47,66538303,2.71861778e+09,35.49,0,2024-10-08 00:00:00+08:00,2024-10-08 00:00:00+08:00
3,SZSE.300979,1d,83.50,85.00,73.92,78.50,11065879,8.68210769e+08,73.91,0,2024-10-08 00:00:00+08:00,2024-10-08 00:00:00+08:00
4,SZSE.300957,1d,73.99,74.00,63.81,70.30,21086484,1.45618655e+09,62.42,0,2024-10-08 00:00:00+08:00,2024-10-08 00:00:00+08:00
...,...,...,...,...,...,...,...,...,...,...,...,...
2091,SHSE.688012,1d,159.00,167.77,158.88,163.46,11122121,1.82186852e+09,169.10,0,2024-10-16 00:00:00+08:00,2024-10-16 00:00:00+08:00
2092,SHSE.600415,1d,11.00,11.07,10.39,10.55,309465631,3.31764278e+09,11.54,0,2024-10-16 00:00:00+08:00,2024-10-16 00:00:00+08:00
2093,SZSE.000876,1d,9.39,9.70,9.30,9.44,34086436,3.22103057e+08,9.44,0,2024-10-16 00:00:00+08:00,2024-10-16 00:00:00+08:00
2094,SZSE.000858,1d,142.00,144.29,140.08,141.65,31227224,4.43054214e+09,144.00,0,2024-10-16 00:00:00+08:00,2024-10-16 00:00:00+08:00
2095,SZSE.301269,1d,88.30,89.99,87.52,89.00,2543410,2.25762367e+08,90.16,0,2024-10-16 00:00:00+08:00,2024-10-16 00:00:00+08:00

In [4]:
history_data

,symbol,frequency,open,high,low,close,volume,amount,pre_close,position,bob,eob
0,SHSE.118037,60s,105.429,105.442,105.029,105.198,1300,136834.0,0.0,0,2024-04-22 09:30:00+08:00,2024-04-22 09:31:00+08:00
1,SHSE.118037,60s,105.201,105.201,105.110,105.110,410,43122.0,0.0,0,2024-04-22 09:31:00+08:00,2024-04-22 09:32:00+08:00
2,SHSE.118037,60s,105.110,105.140,105.029,105.029,420,44143.0,0.0,0,2024-04-22 09:32:00+08:00,2024-04-22 09:33:00+08:00
3,SHSE.118037,60s,105.029,105.029,104.937,104.965,1150,120705.0,0.0,0,2024-04-22 09:33:00+08:00,2024-04-22 09:34:00+08:00
4,SHSE.118037,60s,104.946,105.287,104.900,105.287,810,85030.0,0.0,0,2024-04-22 09:34:00+08:00,2024-04-22 09:35:00+08:00
...,...,...,...,...,...,...,...,...,...,...,...,...
22863,SHSE.118037,60s,106.259,106.399,106.259,106.397,380,40404.0,0.0,0,2024-09-19 14:54:00+08:00,2024-09-19 14:55:00+08:00
22864,SHSE.118037,60s,106.396,106.400,106.259,106.400,1850,196819.0,0.0,0,2024-09-19 14:55:00+08:00,2024-09-19 14:56:00+08:00
22865,SHSE.118037,60s,106.359,106.399,105.934,106.399,370,39327.0,0.0,0,2024-09-19 14:56:00+08:00,2024-09-19 14:57:00+08:00
22866,SHSE.118037,60s,106.399,106.399,106.001,106.001,50,5316.0,0.0,0,2024-09-19 14:57:00+08:00,2024-09-19 14:58:00+08:00
22867,SHSE.118037,60s,106.006,106.294,106.006,106.102,30,3183.0,0.0,0,2024-09-19 14:59:00+08:00,2024-09-19 15:00:00+08:00

In [14]:
hs300_codes

['000012',
 '000016',
 '000019',
 '000025',
 '000028',
 '000029',
 '000030',
 '000034',
 '000035',
 '000048',
 '000049',
 '000058',
 '000059',
 '000061',
 '000062',
 '000065',
 '000088',
 '000090',
 '000403',
 '000415',
 '000420',
 '000422',
 '000426',
 '000429',
 '000488',
 '000498',
 '000503',
 '000517',
 '000528',
 '000543',
 '000550',
 '000552',
 '000555',
 '000557',
 '000567',
 '000581',
 '000582',
 '000597',
 '000600',
 '000603',
 '000627',
 '000628',
 '000650',
 '000657',
 '000672',
 '000676',
 '000681',
 '000682',
 '000685',
 '000686',
 '000688',
 '000690',
 '000712',
 '000718',
 '000719',
 '000727',
 '000735',
 '000736',
 '000737',
 '000756',
 '000758',
 '000761',
 '000762',
 '000766',
 '000767',
 '000791',
 '000795',
 '000801',
 '000810',
 '000811',
 '000813',
 '000821',
 '000828',
 '000829',
 '000837',
 '000848',
 '000860',
 '000869',
 '000875',
 '000881',
 '000885',
 '000901',
 '000902',
 '000913',
 '000915',
 '000917',
 '000923',
 '000927',
 '000928',
 '000935',
 '000950',
 '000951',
 '000966',
 '000968',
 '000969',
 '000970',
 '000990',
 '001213',
 '001236',
 '001258',
 '001269',
 '001270',
 '001287',
 '001301',
 '001308',
 '001309',
 '001311',
 '001322',
 '001323',
 '001337',
 '001338',
 '001376',
 '001696',
 '001914',
 '002003',
 '002004',
 '002006',
 '002010',
 '002011',
 '002015',
 '002020',
 '002023',
 '002034',
 '002036',
 '002038',
 '002041',
 '002043',
 '002048',
 '002051',
 '002053',
 '002060',
 '002061',
 '002063',
 '002068',
 '002075',
 '002077',
 '002079',
 '002081',
 '002085',
 '002088',
 '002091',
 '002096',
 '002097',
 '002099',
 '002100',
 '002101',
 '002108',
 '002123',
 '002125',
 '002126',
 '002127',
 '002130',
 '002135',
 '002139',
 '002145',
 '002151',
 '002154',
 '002158',
 '002163',
 '002171',
 '002174',
 '002176',
 '002182',
 '002183',
 '002190',
 '002191',
 '002192',
 '002194',
 '002204',
 '002212',
 '002214',
 '002215',
 '002216',
 '002219',
 '002221',
 '002222',
 '002226',
 '002233',
 '002237',
 '002239',
 '002242',
 '002243',
 '002245',
 '002249',
 '002250',
 '002254',
 '002258',
 '002265',
 '002267',
 '002270',
 '002274',
 '002275',
 '002276',
 '002283',
 '002287',
 '002291',
 '002292',
 '002302',
 '002312',
 '002314',
 '002315',
 '002317',
 '002318',
 '002320',
 '002324',
 '002332',
 '002335',
 '002349',
 '002351',
 '002354',
 '002378',
 '002389',
 '002390',
 '002396',
 '002400',
 '002402',
 '002405',
 '002416',
 '002421',
 '002428',
 '002434',
 '002446',
 '002453',
 '002456',
 '002458',
 '002461',
 '002467',
 '002468',
 '002484',
 '002488',
 '002489',
 '002498',
 '002511',
 '002516',
 '002534',
 '002537',
 '002539',
 '002541',
 '002544',
 '002545',
 '002549',
 '002550',
 '002567',
 '002581',
 '002583',
 '002585',
 '002597',
 '002605',
 '002612',
 '002617',
 '002626',
 '002635',
 '002643',
 '002646',
 '002649',
 '002651',
 '002675',
 '002681',
 '002697',
 '002698',
 '002701',
 '002705',
 '002706',
 '002726',
 '002727',
 '002737',
 '002745',
 '002746',
 '002747',
 '002761',
 '002773',
 '002777',
 '002782',
 '002807',
 '002815',
 '002832',
 '002837',
 '002839',
 '002840',
 '002847',
 '002851',
 '002859',
 '002891',
 '002895',
 '002901',
 '002906',
 '002911',
 '002913',
 '002925',
 '002928',
 '002929',
 '002941',
 '002946',
 '002948',
 '002959',
 '002960',
 '002961',
 '002967',
 '002978',
 '002985',
 '002987',
 '002990',
 '002991',
 '002993',
 '003006',
 '003009',
 '003012',
 '003021',
 '003039',
 '003040',
 '300026',
 '300027',
 '300031',
 '300034',
 '300035',
 '300036',
 '300039',
 '300045',
 '300049',
 '300065',
 '300068',
 '300075',
 '300077',
 '300079',
 '300080',
 '300083',
 '300085',
 '300087',
 '300101',
 '300109',
 '300113',
 '300115',
 '300119',
 '300123',
 '300129',
 '300130',
 '300133',
 '300134',
 '300140',
 '300143',
 '300151',
 '300166',
 '300170',
 '300171',
 '300180',
 '300182',
 '300183',
 '300185',
 '300188',
 '300203',
 '300206',
 '300224',
 '300226',
 '300229',
 '300232',
 '300233',
 '300236',
 '300244',
 '300257',
 '300260',
 '300261',
 '300263',
 '300267',
 '300284',
 '300294',
 '300298',
 '300303',
 '300315',
 '300319',
 '300323',
 '300327',
 '300332',
 '300339',
 '300343',
 '300346',
 '300348',
 '300352',
 '300358',
 '300363',
 '300366',
 '300369',
 '300379',
 '300382',
 '300393',
 '300398',
 '300406',
 '300409',
 '300415',
 '300416',
 '300428',
 '300432',
 '300443',
 '300446',
 '300451',
 '300455',
 '300456',
 '300457',
 '300458',
 '300459',
 '300463',
 '300470',
 '300475',
 '300476',
 '300482',
 '300525',
 '300527',
 '300570',
 '300573',
 '300576',
 '300579',
 '300587',
 '300593',
 '300596',
 '300598',
 '300602',
 '300613',
 '300618',
 '300620',
 '300623',
 '300624',
 '300627',
 '300633',
 '300634',
 '300638',
 '300655',
 '300660',
 '300663',
 '300666',
 '300671',
 '300672',
 '300674',
 '300678',
 '300679',
 '300685',
 '300687',
 '300693',
 '300702',
 '300705',
 '300723',
 '300725',
 '300726',
 '300735',
 '300737',
 '300738',
 '300741',
 '300747',
 '300755',
 '300757',
 '300761',
 '300762',
 '300768',
 '300770',
 '300772',
 '300773',
 '300775',
 '300777',
 '300783',
 '300811',
 '300820',
 '300821',
 '300827',
 '300841',
 '300850',
 '300855',
 '300856',
 '300857',
 '300860',
 '300869',
 '300887',
 '300894',
 '300910',
 '300953',
 '300973',
 '301015',
 '301031',
 '301035',
 '301039',
 '301047',
 '301050',
 '301069',
 '301071',
 '301078',
 '301080',
 '301087',
 '301089',
 '301090',
 '301095',
 '301153',
 '301155',
 '301171',
 '301175',
 '301177',
 '301180',
 '301205',
 '301207',
 '301216',
 '301217',
 '301219',
 '301238',
 '301239',
 '301246',
 '301262',
 '301268',
 '301291',
 '301293',
 '301301',
 '301308',
 '301316',
 '301325',
 '301327',
 '301339',
 '301348',
 '301363',
 '301367',
 '301371',
 '301376',
 '301381',
 '301487',
 '301498',
 '301500',
 '301510',
 '301511',
 '301526',
 '301558',
 '301559',
 '600006',
 '600007',
 '600012',
 '600017',
 '600033',
 '600037',
 '600055',
 '600057',
 '600058',
 '600059',
 '600063',
 '600064',
 '600072',
 '600073',
 '600075',
 '600100',
 '600110',
 '600116',
 '600120',
 '600123',
 '600125',
 '600138',
 '600151',
 '600158',
 '600163',
 '600169',
 '600179',
 '600185',
 '600195',
 '600197',
 '600201',
 '600206',
 '600210',
 '600211',
 '600216',
 '600217',
 '600223',
 '600225',
 '600246',
 '600248',
 '600252',
 '600259',
 '600266',
 '600267',
 '600269',
 '600273',
 '600285',
 '600295',
 '600301',
 '600305',
 '600312',
 '600313',
 '600320',
 '600323',
 '600328',
 '600330',
 '600331',
 '600335',
 '600338',
 '600340',
 '600363',
 '600366',
 '600389',
 '600391',
 '600395',
 '600400',
 '600403',
 '600409',
 '600420',
 '600422',
 '600428',
 '600446',
 '600449',
 '600452',
 '600456',
 '600458',
 '600459',
 '600461',
 '600475',
 '600477',
 '600478',
 '600480',
 '600490',
 '600491',
 '600496',
 '600502',
 '600507',
 '600508',
 '600509',
 '600531',
 '600550',
 '600552',
 '600556',
 '600557',
 '600559',
 '600562',
 '600572',
 '600575',
 '600577',
 '600586',
 '600587',
 '600595',
 '600596',
 '600597',
 '600601',
 '600602',
 '600604',
 '600610',
 '600618',
 '600621',
 '600623',
 '600633',
 '600635',
 '600639',
 '600641',
 '600643',
 '600645',
 '600648',
 '600649',
 '600651',
 '600657',
 '600662',
 '600667',
 '600675',
 '600682',
 '600685',
 '600688',
 '600691',
 '600710',
 '600717',
 '600718',
 '600720',
 '600728',
 '600729',
 '600740',
 '600750',
 '600751',
 '600757',
 '600761',
 '600771',
 '600773',
 '600775',
 '600776',
 '600780',
 '600782',
 '600783',
 '600787',
 '600797',
 '600810',
 '600811',
 '600812',
 '600821',
 '600835',
 '600850',
 '600861',
 '600864',
 '600869',
 '600874',
 '600877',
 '600882',
 '600888',
 '600903',
 '600908',
 '600916',
 '600929',
 '600933',
 '600961',
 '600963',
 '600966',
 '600971',
 '600976',
 '600986',
 '600993',
 '600996',
 '600997',
 '601001',
 '601011',
 '601015',
 '601022',
 '601028',
 '601033',
 '601038',
 '601068',
 '601069',
 '601083',
 '601096',
 '601099',
 '601101',
 '601107',
 '601126',
 '601137',
 '601163',
 '601187',
 '601200',
 '601208',
 '601222',
 '601279',
 '601311',
 '601326',
 '601333',
 '601369',
 '601375',
 '601515',
 '601519',
 '601528',
 '601595',
 '601606',
 '601609',
 '601619',
 '601677',
 '601678',
 '601702',
 '601718',
 '601777',
 '601778',
 '601801',
 '601811',
 '601860',
 '601869',
 '601882',
 '601886',
 '601890',
 '601908',
 '601918',
 '601921',
 '601949',
 '601952',
 '601963',
 '601969',
 '601975',
 '603005',
 '603008',
 '603013',
 '603025',
 '603026',
 '603027',
 '603033',
 '603039',
 '603043',
 '603055',
 '603057',
 '603063',
 '603071',
 '603075',
 '603083',
 '603093',
 '603098',
 '603100',
 '603103',
 '603105',
 '603108',
 '603113',
 '603118',
 '603123',
 '603128',
 '603129',
 '603132',
 '603162',
 '603169',
 '603170',
 '603171',
 '603187',
 '603197',
 '603212',
 '603220',
 '603229',
 '603236',
 '603267',
 '603279',
 '603281',
 '603283',
 '603297',
 '603299',
 '603300',
 '603301',
 '603306',
 '603308',
 '603323',
 '603327',
 '603328',
 '603348',
 '603358',
 '603368',
 '603383',
 '603393',
 '603398',
 '603439',
 '603466',
 '603477',
 '603489',
 '603505',
 '603530',
 '603533',
 '603556',
 '603565',
 '603566',
 '603567',
 '603583',
 '603588',
 '603595',
 '603599',
 '603609',
 '603612',
 '603636',
 '603638',
 '603666',
 '603678',
 '603690',
 '603693',
 '603699',
 '603713',
 '603718',
 '603719',
 '603730',
 '603733',
 '603766',
 '603801',
 '603866',
 '603871',
 '603876',
 '603877',
 '603881',
 '603888',
 '603896',
 '603906',
 '603915',
 '603919',
 '603920',
 '603936',
 '603938',
 '603983',
 '603985',
 '603989',
 '603995',
 '603997',
 '605009',
 '605011',
 '605020',
 '605090',
 '605111',
 '605123',
 '605168',
 '605222',
 '605333',
 '605365',
 '605376',
 '605507',
 '605589',
 '605599',
 '688001',
 '688007',
 '688016',
 '688018',
 '688019',
 '688023',
 '688027',
 '688031',
 '688033',
 '688037',
 '688046',
 '688048',
 '688050',
 '688062',
 '688066',
 '688076',
 '688083',
 '688088',
 '688091',
 '688097',
 '688100',
 '688105',
 '688106',
 '688110',
 '688116',
 '688123',
 '688127',
 '688128',
 '688131',
 '688139',
 '688141',
 '688146',
 '688147',
 '688152',
 '688158',
 '688161',
 '688166',
 '688167',
 '688173',
 '688177',
 '688183',
 '688185',
 '688190',
 '688192',
 '688202',
 '688206',
 '688208',
 '688209',
 '688232',
 '688235',
 '688239',
 '688261',
 '688262',
 '688266',
 '688268',
 '688270',
 '688278',
 '688279',
 '688289',
 '688298',
 '688300',
 '688315',
 '688318',
 '688321',
 '688322',
 '688326',
 '688327',
 '688332',
 '688333',
 '688336',
 '688337',
 '688339',
 '688343',
 '688351',
 '688352',
 '688362',
 '688366',
 '688368',
 '688372',
 '688380',
 '688381',
 '688383',
 '688388',
 '688389',
 '688392',
 '688400',
 '688403',
 '688408',
 '688409',
 '688432',
 '688433',
 '688439',
 '688484',
 '688498',
 '688502',
 '688503',
 '688508',
 '688515',
 '688518',
 '688526',
 '688531',
 '688556',
 '688559',
 '688568',
 '688575',
 '688578',
 '688586',
 '688596',
 '688598',
 '688608',
 '688630',
 '688639',
 '688658',
 '688676',
 '688680',
 '688686',
 '688690',
 '688696',
 '688700',
 '688707',
 '688711',
 '688739',
 '688776',
 '688789',
 '688798',
 '688800']

000012
000016
000019
000025
000028
000029
000030
000034
000035
000048
000049
000058
000059
000061
000062
000065
000088
000090
000403
000415
000420
000422
000426
000429
000488
000498
000503
000517
000528
000543
000550
000552
000555
000557
000567
000581
000582
000597
000600
000603
000627
000628
000650
000657
000672
000676
000681
000682
000685
000686
000688
000690
000712
000718
000719
000727
000735
000736
000737
000756
000758
000761
000762
000766
000767
000791
000795
000801
000810
000811
000813
000821
000828
000829
000837
000848
000860
000869
000875
000881
000885
000901
000902
000913
000915
000917
000923
000927
000928
000935
000950
000951
000966
000968
000969
000970
000990
001213
001236
001258
001269
001270
001287
001301
001308
001309
001311
001322
001323
001337
001338
001376
001696
001914
002003
002004
002006
002010
002011
002015
002020
002023
002034
002036
002038
002041
002043
002048
002051
002053
002060
002061
002063
002068
002075
002077
002079
002081
002085
002088
002091
002096
002097
002099
002100
002101
002108
002123
002125
002126
002127
002130
002135
002139
002145
002151
002154
002158
002163
002171
002174
002176
002182
002183
002190
002191
002192
002194
002204
002212
002214
002215
002216
002219
002221
002222
002226
002233
002237
002239
002242
002243
002245
002249
002250
002254
002258
002265
002267
002270
002274
002275
002276
002283
002287
002291
002292
002302
002312
002314
002315
002317
002318
002320
002324
002332
002335
002349
002351
002354
002378
002389
002390
002396
002400
002402
002405
002416
002421
002428
002434
002446
002453
002456
002458
002461
002467
002468
002484
002488
002489
002498
002511
002516
002534
002537
002539
002541
002544
002545
002549
002550
002567
002581
002583
002585
002597
002605
002612
002617
002626
002635
002643
002646
002649
002651
002675
002681
002697
002698
002701
002705
002706
002726
002727
002737
002745
002746
002747
002761
002773
002777
002782
002807
002815
002832
002837
002839
002840
002847
002851
002859
002891
002895
002901
002906
002911
002913
002925
002928
002929
002941
002946
002948
002959
002960
002961
002967
002978
002985
002987
002990
002991
002993
003006
003009
003012
003021
003039
003040
300026
300027
300031
300034
300035
300036
300039
300045
300049
300065
300068
300075
300077
300079
300080
300083
300085
300087
300101
300109
300113
300115
300119
300123
300129
300130
300133
300134
300140
300143
300151
300166
300170
300171
300180
300182
300183
300185
300188
300203
300206
300224
300226
300229
300232
300233
300236
300244
300257
300260
300261
300263
300267
300284
300294
300298
300303
300315
300319
300323
300327
300332
300339
300343
300346
300348
300352
300358
300363
300366
300369
300379
300382
300393
300398
300406
300409
300415
300416
300428
300432
300443
300446
300451
300455
300456
300457
300458
300459
300463
300470
300475
300476
300482
300525
300527
300570
300573
300576
300579
300587
300593
300596
300598
300602
300613
300618
300620
300623
300624
300627
300633
300634
300638
300655
300660
300663
300666
300671
300672
300674
300678
300679
300685
300687
300693
300702
300705
300723
300725
300726
300735
300737
300738
300741
300747
300755
300757
300761
300762
300768
300770
300772
300773
300775
300777
300783
300811
300820
300821
300827
300841
300850
300855
300856
300857
300860
300869
300887
300894
300910
300953
300973
301015
301031
301035
301039
301047
301050
301069
301071
301078
301080
301087
301089
301090
301095
301153
301155
301171
301175
301177
301180
301205
301207
301216
301217
301219
301238
301239
301246
301262
301268
301291
301293
301301
301308
301316
301325
301327
301339
301348
301363
301367
301371
301376
301381
301487
301498
301500
301510
301511
301526
301558
301559
600006
600007
600012
600017
600033
600037
600055
600057
600058
600059
600063
600064
600072
600073
600075
600100
600110
600116
600120
600123
600125
600138
600151
600158
600163
600169
600179
600185
600195
600197
600201
600206
600210
600211
600216
600217
600223
600225
600246
600248
600252
600259
600266
600267
600269
600273
600285
600295
600301
600305
600312
600313
600320
600323
600328
600330
600331
600335
600338
600340
600363
600366
600389
600391
600395
600400
600403
600409
600420
600422
600428
600446
600449
600452
600456
600458
600459
600461
600475
600477
600478
600480
600490
600491
600496
600502
600507
600508
600509
600531
600550
600552
600556
600557
600559
600562
600572
600575
600577
600586
600587
600595
600596
600597
600601
600602
600604
600610
600618
600621
600623
600633
600635
600639
600641
600643
600645
600648
600649
600651
600657
600662
600667
600675
600682
600685
600688
600691
600710
600717
600718
600720
600728
600729
600740
600750
600751
600757
600761
600771
600773
600775
600776
600780
600782
600783
600787
600797
600810
600811
600812
600821
600835
600850
600861
600864
600869
600874
600877
600882
600888
600903
600908
600916
600929
600933
600961
600963
600966
600971
600976
600986
600993
600996
600997
601001
601011
601015
601022
601028
601033
601038
601068
601069
601083
601096
601099
601101
601107
601126
601137
601163
601187
601200
601208
601222
601279
601311
601326
601333
601369
601375
601515
601519
601528
601595
601606
601609
601619
601677
601678
601702
601718
601777
601778
601801
601811
601860
601869
601882
601886
601890
601908
601918
601921
601949
601952
601963
601969
601975
603005
603008
603013
603025
603026
603027
603033
603039
603043
603055
603057
603063
603071
603075
603083
603093
603098
603100
603103
603105
603108
603113
603118
603123
603128
603129
603132
603162
603169
603170
603171
603187
603197
603212
603220
603229
603236
603267
603279
603281
603283
603297
603299
603300
603301
603306
603308
603323
603327
603328
603348
603358
603368
603383
603393
603398
603439
603466
603477
603489
603505
603530
603533
603556
603565
603566
603567
603583
603588
603595
603599
603609
603612
603636
603638
603666
603678
603690
603693
603699
603713
603718
603719
603730
603733
603766
603801
603866
603871
603876
603877
603881
603888
603896
603906
603915
603919
603920
603936
603938
603983
603985
603989
603995
603997
605009
605011
605020
605090
605111
605123
605168
605222
605333
605365
605376
605507
605589
605599
688001
688007
688016
688018
688019
688023
688027
688031
688033
688037
688046
688048
688050
688062
688066
688076
688083
688088
688091
688097
688100
688105
688106
688110
688116
688123
688127
688128
688131
688139
688141
688146
688147
688152
688158
688161
688166
688167
688173
688177
688183
688185
688190
688192
688202
688206
688208
688209
688232
688235
688239
688261
688262
688266
688268
688270
688278
688279
688289
688298
688300
688315
688318
688321
688322
688326
688327
688332
688333
688336
688337
688339
688343
688351
688352
688362
688366
688368
688372
688380
688381
688383
688388
688389
688392
688400
688403
688408
688409
688432
688433
688439
688484
688498
688502
688503
688508
688515
688518
688526
688531
688556
688559
688568
688575
688578
688586
688596
688598
688608
688630
688639
688658
688676
688680
688686
688690
688696
688700
688707
688711
688739
688776
688789
688798
688800
Empty DataFrame
Columns: [股票代码, 日期, 收盘]
Index: []

In [8]:
stock_data = ak.stock_zh_a_hist(symbol=stock_code, period="daily", start_date="20220101", end_date="20231231")
# 计算60日最低价
# stock_data['60_day_low'] = stock_data['最低价'].rolling(window=60).min()

KeyError: '最低价'

In [9]:
stock_data

,日期,股票代码,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,2022-01-04,688981,53.10,53.14,53.22,52.80,138316,732844656.0,0.79,0.28,0.15,0.74
1,2022-01-05,688981,53.22,52.88,53.22,52.67,167429,885473648.0,1.04,-0.49,-0.26,0.89
2,2022-01-06,688981,52.70,52.80,53.03,52.69,119781,633215552.0,0.64,-0.15,-0.08,0.64
3,2022-01-07,688981,52.96,52.83,53.07,52.80,128315,678678032.0,0.51,0.06,0.03,0.69
4,2022-01-10,688981,52.98,52.88,52.99,52.69,110513,583786544.0,0.57,0.09,0.05,0.59
...,...,...,...,...,...,...,...,...,...,...,...,...
479,2023-12-25,688981,54.60,53.01,55.00,52.85,177884,954109664.0,3.92,-3.25,-1.78,0.90
480,2023-12-26,688981,53.01,51.85,53.23,51.80,144016,754093590.0,2.70,-2.19,-1.16,0.73
481,2023-12-27,688981,51.83,51.91,52.29,51.18,151735,786451367.0,2.14,0.12,0.06,0.77
482,2023-12-28,688981,51.70,53.13,53.45,51.68,192119,1015242627.0,3.41,2.35,1.22,0.97
483,2023-12-29,688981,53.00,53.02,53.50,52.88,126487,671919217.0,1.17,-0.21,-0.11,0.64